services:
  - type: web
    name: comisiones-marinas-prod
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && gunicorn run:app --bind 0.0.0.0:$PORT --worker-class eventlet --timeout 120 --workers 1"
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production  
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: comisiones-db-prod
          property: connectionString
      - key: ADMIN_EMAIL
        value: admin@comisionesmarinas.es
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: WEB_CONCURRENCY
        value: "1"
      # CLOUDINARY - Con la configuración corregida
      - key: CLOUDINARY_CLOUD_NAME
        value: dme0c3e49
      - key: CLOUDINARY_API_KEY
        value: 832563841778816
      - key: CLOUDINARY_API_SECRET
        value: ofN6hvae3Mh10yZb_wAO9MBT1jU
      # RESEND - Con tu API key real
      - key: RESEND_API_KEY
        value: re_3WMiQcKv_6Ze96P2s6kbJfYf2cHA3sr5H
      - key: RESEND_FROM_EMAIL
        value: "Comisiones Marinas <noreply@comisionesmarinas.es>"
    plan: starter
    healthCheckPath: /health

databases:
  - name: comisiones-db-prod
    databaseName: comisiones_prod
    user: comisiones_user_prod
    plan: starter
